name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12.x
        uses: actions/setup-node@v3
        with:
          node-version: "12.x"
          cache: "npm"

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build:production

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "."
          target: "/home/cyril/cyrildeschamps"

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            docker stop portfolio
            docker rm portfolio
            docker build -t portfolio /home/cyril/cyrildeschamps/
            docker run -d --name portfolio -p 80:80 -t portfolio

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: cache clean
